name: Run Tests with CI
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "20"
runs:
  using: "composite"
  steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Install NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      shell: bash
      run: npm install
    - name: Run tests
      id: run-tests
      shell: bash
      run: npm run test:ci
    - name: Upload test report
      if: failure() && steps.run-tests.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test.json
